# LOCAL(DEFAULT)
server:
  port: 8080
spring:
  config:
    activate:
      on-profile: local
  thymeleaf:
    cache: false
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

  datasource:
    url: jdbc:p6spy:h2:tcp://localhost/~/aladdinsys-api;
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    username: aladdin
    password:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: false
  output:
    ansi:
      enabled: always

  decorator:
    datasource:
      p6spy:
        enable-logging: true

#logging:
#  level: # 적용할 곳과 레벨을 지정합니다.
#    root: WARN
#    org:
#      hibernate:
#        SQL: INFO
#        type:
#          descriptor:
#            sql:
#              BasicBinder: trace
#  file:
#    name: C:/Dev/aladdin-logs/api/logging.log
#  logback:
#    rolling-policy:
#      file-name-pattern: C:/Dev/aladdin-logs/api/%d{yyyy-MM-dd}_%i.gz
#  pattern:
#    file: "[%d{yyyy-MM-dd HH:mm:ss}:%-4relative] [%thread] %-5level %logger{35} - %msg%n"