# LOCAL(DEFAULT)
server:
  port: 8080
spring:
  config:
    activate:
      on-profile: local
  thymeleaf:
    cache: false
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

  datasource:
    url: jdbc:p6spy:h2:tcp://localhost/~/aladdinsys-api;
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    username: aladdin
    password:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: false
  output:
    ansi:
      enabled: always