### Post Request
POST {{domain}}:{{port}}/departments
Content-Type: application/json

{
  "name": "부서"
}

### Get Request
GET {{domain}}:{{port}}/departments

### Get One Request
GET {{domain}}:{{port}}/departments/1

### Put Request
PUT {{domain}}:{{port}}/departments/2
Content-Type: application/json

{
  "name": "부서_수정"
}

