### Post Request
POST {{domain}}:{{port}}/{{context-path}}/employees
Content-Type: application/json

{
  "departmentId": 1,
  "name": "직원2"
}

### Get Request
GET {{domain}}:{{port}}/{{context-path}}/employees

### Get One Request
GET {{domain}}:{{port}}/{{context-path}}/employees/1

### Get By Department Request
GET {{domain}}:{{port}}/{{context-path}}/departments/1/employees

### Put Request
PUT {{domain}}:{{port}}/{{context-path}}/employees/1
Content-Type: application/json

{
  "name": "직원_PUT",
  "departmentId": 2
}


### Patch Request
PATCH {{domain}}:{{port}}/{{context-path}}/employees/1
Content-Type: application/json

{
  "name": "직원_PATCH"
}


### Delete Request
DELETE {{domain}}:{{port}}/{{context-path}}/employees/1
